#! /bin/sh
#  /etc/init.d/heizung

### BEGIN INIT INFO
# Provides:          heizung
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Short-Description: Starts the Heizung Steuerung service
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       This file is used to start the daemon
#                    and should be placed in /etc/init.d
### END INIT INFO

# Author:   Sheldon Neilson <sheldon[AT]neilson.co.za>
# Url:      www.neilson.co.za
# Date:     25/04/2013

NAME="heizung.jar"
DESC="Heizungssteuerung"

# The path to Jsvc
EXEC="/usr/bin/jsvc"

# The path to the folder containing MyDaemon.jar
FILE_PATH="/opt/"

# The path to the folder containing the java runtime
JAVA_HOME="/usr/lib/jvm/java-8-openjdk-armhf" #"/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt"
#JAVA_HOME="/usr/lib/jvm/java-10-openjdk-armhf"

# Our classpath including our jar file and the Apache Commons Daemon library
CLASS_PATH="$FILE_PATH/heizung.jar:/usr/share/java/commons-daemon.jar"

# The fully qualified name of the class to execute
CLASS="de.recondita.heizung.server.Service"

# Any command line arguments to be passed to the our Java Daemon implementations init() method
ARGS="/home/heizung/config"

#The user to run the daemon as
USER="heizung"

# The file that will contain our process identification number (pid) for other scripts/programs that need to access it.
PID="/var/run/$NAME.pid"

# System.out writes to this file...
LOG_OUT="/home/heizung/syso.log"

# System.err writes to this file...
LOG_ERR="/var/log/heizung.log"

jsvc_exec()
{
    cd /home/$USER
    $EXEC -home $JAVA_HOME -cp $CLASS_PATH -user $USER -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS $ARGS
}

case "$1" in
    start)
        echo "Starting the $DESC..."
        # Start the service
        jsvc_exec
        echo "The $DESC has started."
    ;;
    stop)
        echo "Stopping the $DESC..."
        # Stop the service
        jsvc_exec "-stop"
        echo "The $DESC has stopped."
    ;;
    restart)
        if [ -f "$PID" ]; then
            echo "Restarting the $DESC..."
            # Stop the service
            jsvc_exec "-stop"
            # Start the service
            jsvc_exec
            echo "The $DESC has restarted."
        else
            echo "Daemon not running, no action taken"
            exit 1
        fi
            ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 3
    ;;
esac
